version: '3.7'

services:
    inka-api-nginx:
        container_name: "inka-api-nginx"
        build:
          dockerfile: ./.docker/nginx/Dockerfile
          context: ./
        networks:
            - inka-network
    inka-api-prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./.docker/nestjs/Dockerfile
        command: npm run start:prod
        dns:
            - 8.8.8.8
            - 4.4.4.4
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - inka-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - inka-network
        restart: unless-stopped
networks:
    inka-network:
        external: true