version: '3.7'

services:
    transaction-api-dev:
        container_name: transaction-api-dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./.docker/nestjs/Dockerfile
        command: npm run start:debug
        dns:
            - 8.8.8.8
            - 4.4.4.4
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - hackaton-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
    transaction-postgres:
        container_name: transaction-postgres
        image: postgres:11-alpine
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USERNAME}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - TZ=Europe/Moscow
            - PGTZ=Europe/Moscow
        ports:
            - ${DATABASE_PORT}:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - hackaton-network

volumes:
  pgdata:

networks:
    hackaton-network:
      external: true